services:
  - docker

install:
  - docker build -t wiotp/gateway-lightify:$TRAVIS_BRANCH .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push wiotp/gateway-lightify:$TRAVIS_BRANCH

