language: minimal

services:
  - docker

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t wiotp/gateway-lightify:$TRAVIS_BRANCH .
  - docker push wiotp/gateway-lightify:$TRAVIS_BRANCH
  - |
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker tag wiotp/gateway-lightify:$TRAVIS_BRANCH wiotp/gateway-lightify:latest
      docker push wiotp/gateway-lightify:latest
    fi
